CREATE TABLE CLIENT (
  ID_CLIENT INTEGER,
  CPF VARCHAR(10) NOT NULL,
  NAME VARCHAR NOT NULL,
  TELEPHONE VARCHAR(12) NOT NULL,
  PRIMARY KEY(ID_CLIENT)
);

CREATE TABLE MODEL(
  ID_MODEL INTEGER,
  DES_MODEL VARCHAR(30) NOT NULL,
  PRIMARY KEY(ID_MODEL)
);

CREATE TABLE COLOR(
  ID_COLOR INTEGER,
  DES_COLOR VARCHAR(30) NOT NULL,
  PRIMARY KEY(ID_COLOR)
);

CREATE TABLE VEHICLE(
  ID_VEHICLE INTEGER,
  PLATE VARCHAR(10) NOT NULL,
  ID_COLOR INTEGER NOT NULL,
  ID_MODEL INTEGER NOT NULL,
  ID_CLIENT INTEGER NOT NULL,
  PRIMARY KEY (ID_VEHICLE),
  FOREIGN KEY(ID_MODEL) REFERENCES MODEL(ID_MODEL),
  FOREIGN KEY(ID_COLOR) REFERENCES COLOR(ID_COLOR)
);

CREATE SEQUENCE SEQ_ID_MODEL   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_COLOR   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_VEHICLE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ID_CLIENT  START WITH 1 INCREMENT BY 1;

INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'FORD');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'FIAT');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'WOLKSWAGEM');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'PEUGEOT');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'TOYOTA');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'BMW');
INSERT INTO MODEL (ID_MODEL, DES_MODEL) VALUES (SEQ_ID_MODEL.NEXTVAL, 'OUTRA');

INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'PRETO');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'PRATA');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'BRANCO');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'VERMELHO');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'AMARELO');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'ROSA');
INSERT INTO COLOR (ID_COLOR, DES_COLOR) VALUES (SEQ_ID_COLOR.NEXTVAL, 'OUTRA');


